#!/usr/bin/env python3
"""Generate the deterministic CUDA default-rule header."""

from __future__ import annotations

import argparse
import os
from pathlib import Path
import sys
import tempfile
from typing import Optional


PROJECT_ROOT = Path(__file__).resolve().parents[1]
if str(PROJECT_ROOT) not in sys.path:
    sys.path.insert(0, str(PROJECT_ROOT))

import rare_rules  # noqa: E402  (project root is intentionally inserted first)


DEFAULT_OUTPUT = PROJECT_ROOT / "generated" / "rare_rules_default.cuh"


def render_header(ruleset: rare_rules.RareRuleset) -> str:
    active = ruleset.active_rules
    lines = [
        "#pragma once",
        "// Generated by tools/generate_rare_rules.py; do not edit by hand.",
        "namespace meshcore_rare_generated {",
        f"constexpr unsigned int kSchemaVersion = {ruleset.schema_version}U;",
        ("constexpr unsigned int kCudaRuleProtocolVersion = "
         f"{rare_rules.CUDA_RULE_PROTOCOL_VERSION}U;"),
        f'constexpr char kRulesetId[] = "{ruleset.ruleset_id}";',
        f'constexpr char kRulesetFingerprint[] = "{ruleset.fingerprint}";',
        f"constexpr unsigned int kRuleCount = {len(active)}U;",
        "struct RareRuleSpec {",
        "    unsigned char kind;",
        "    unsigned char minimum_nibbles;",
        "    unsigned short excluded_mask;",
        "    char value[65];",
        "};",
        "constexpr RareRuleSpec kRules[] = {",
    ]
    for rule in active:
        lines.append(
            f'    {{{rule.kind_code}, {rule.threshold_length}, '
            f'0x{rule.excluded_mask:04x}, "{rule.value}"}},'
        )
    lines.extend((
        "};",
        "constexpr const char *kTriggers[] = {",
    ))
    for rule in active:
        lines.append(f'    "{rule.trigger}",')
    lines.extend((
        "};",
        "",
        "// This classifier is generated from the same canonical rules as the",
        "// host metadata above. Helper templates are supplied by cuda_vanity.cu.",
        "__device__ __forceinline__ int classify_generated_default(const unsigned char *key) {",
    ))
    for index, rule in enumerate(active):
        if rule.kind == "bookend":
            expression = f"rare_static_bookend<{rule.threshold_length}>(key)"
        elif rule.kind == "mirror":
            expression = f"rare_static_mirror<{rule.threshold_length}>(key)"
        elif rule.kind == "repeat-prefix":
            expression = (
                f"rare_static_repeat<{rule.threshold_length}, "
                f"0x{rule.excluded_mask:04x}U>(key)"
            )
        else:
            nibbles = ", ".join(
                f"0x{int(character, 16):x}U"
                for character in rule.value[:rule.threshold_length]
            )
            expression = f"rare_static_literal<{nibbles}>(key)"
        lines.append(f"    if ({expression}) return {index};")
    lines.extend((
        "    return -1;",
        "}",
        "}  // namespace meshcore_rare_generated",
        "",
    ))
    return "\n".join(lines)


def write_if_changed(path: Path, content: str) -> bool:
    """Atomically replace path only when its exact contents differ."""
    encoded = content.encode("utf-8")
    try:
        if path.read_bytes() == encoded:
            return False
    except FileNotFoundError:
        pass
    path.parent.mkdir(parents=True, exist_ok=True)
    descriptor, temporary_name = tempfile.mkstemp(
        prefix=f".{path.name}.", suffix=".tmp", dir=path.parent
    )
    temporary = Path(temporary_name)
    try:
        os.fchmod(descriptor, 0o644)
        with os.fdopen(descriptor, "wb") as file:
            file.write(encoded)
            file.flush()
            os.fsync(file.fileno())
        os.replace(temporary, path)
    finally:
        try:
            temporary.unlink()
        except FileNotFoundError:
            pass
    return True


def build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--input", type=Path, default=rare_rules.DEFAULT_RULES_PATH)
    parser.add_argument("--output", type=Path, default=DEFAULT_OUTPUT)
    parser.add_argument(
        "--check", action="store_true",
        help="return failure if the output is missing or differs; never write",
    )
    return parser


def main(argv: Optional[list[str]] = None) -> int:
    arguments = build_parser().parse_args(argv)
    try:
        ruleset = rare_rules.load_ruleset(arguments.input)
        expected = render_header(ruleset)
    except rare_rules.RuleConfigError as error:
        print(f"rare-rule generation failed: {error}", file=sys.stderr)
        return 2
    if arguments.check:
        try:
            current = arguments.output.read_text(encoding="utf-8")
        except (OSError, UnicodeDecodeError):
            current = None
        if current != expected:
            print(
                f"generated rare-rule header is stale: {arguments.output}",
                file=sys.stderr,
            )
            return 1
        return 0
    try:
        write_if_changed(arguments.output, expected)
    except OSError as error:
        print(f"could not write generated rare-rule header: {arguments.output}",
              file=sys.stderr)
        return 2
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
